# Generated by Django 4.1.11 on 2023-09-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
