# Generated by Django 4.1.11 on 2023-09-21 07:50

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0002_commande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plats',
            name='id',
        ),
        migrations.AddField(
            model_name='plats',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
    ]
