# Generated by Django 4.1.11 on 2023-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
