# Generated by Django 4.1.11 on 2023-09-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0003_alter_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
