# Generated by Django 4.1.11 on 2023-09-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0004_delete_panier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
