# Generated by Django 4.1.11 on 2023-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0006_alter_livreur_availability_alter_plats_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='location',
            field=models.CharField(default='Paris, ile de france', max_length=100),
        ),
    ]
