# Generated by Django 4.1.11 on 2023-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpressFoodApp', '0008_rename_client_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
