# Utilisation de l'image officielle Python 3.8
FROM python:3.8

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers de requirements.txt dans le conteneur
COPY requirements.txt /app/

# Installation des dépendances Python
RUN pip install -r requirements.txt

# Copie de tous les fichiers du projet Django dans le conteneur
COPY . /app/

# Exécution des migrations et de la collecte statique des fichiers Django
# RUN python manage.py migrate
# RUN python manage.py collectstatic --noinput

# Définir les variables d'environnement
ENV DJANGO_SETTINGS_MODULE=myproject.settings

# Exposer le port 8000 pour le serveur web Django
EXPOSE 8000

# Commande pour démarrer le serveur web Django
CMD ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
